name: Build grub from source

permissions:
  contents: write
  
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    steps:
    - name: Parse tag
      id: semver_parser 
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ github.ref }}
        version_extractor_regex: '\/(.*)$'
        
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential cdbs devscripts equivs fakeroot flex bison help2man texinfo xfonts-unifont libfreetype6-dev libdevmapper-dev libsdl1.2-dev xorriso parted libfuse-dev fonts-dejavu-core liblzma-dev dosfstools mtools wamerican pkg-config bash-completion libefiboot-dev libefivar-dev python3 gcc gawk xorriso
        sudo apt-get clean
        
    - name: Fetch sources
      run: git clone https://git.savannah.gnu.org/git/grub.git --branch grub-${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }} --depth 1

    - name: Bootstrap
      working-directory: ./grub
      run: ./bootstrap

    - name: Configure
      working-directory: ./grub
      run: ./configure --prefix="$HOME/opt/grub" --target=${{ steps.semver_parser.outputs.prerelease }} --with-platform=efi

    - name: Install
      working-directory: ./grub
      run: make install

    - name: Build image
      working-directory: ./grub
      run: $HOME/opt/grub/bin/grub-mkrescue -o grub.iso

    - name: Upload image
      uses: softprops/action-gh-release@v2
      with:
        files: grub/grub.iso
